
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    loadbalancer:
      enabled: true
    gateway:
      routes:
        - id: test-service
          uri: lb://TEST-SERVICE
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
